# Generated by Django 4.2.4 on 2023-08-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Planet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the planet", max_length=250
                    ),
                ),
                ("population", models.BigIntegerField(null=True)),
                ("_terrains", models.TextField(db_column="terrains", null=True)),
                ("_climates", models.TextField(db_column="climates", null=True)),
            ],
        ),
    ]
